# rag.py
# ---------------------------------------------------------------------------
# PURPOSE:
#   Core RAG pipeline — uses Groq for chat and local embeddings for retrieval.
#
#   RAG steps:
#     1. RETRIEVE  — find relevant chunks from FAISS using local embeddings
#     2. AUGMENT   — inject those chunks as context into the prompt
#     3. GENERATE  — Groq LLM (llama3-8b-8192) answers using only that context
#
#   This file does NOT import from itself. Imports are:
#     - groq        (for chat completions)
#     - embeddings  (for load_index and search_index)
#     - dotenv      (for reading GROQ_API_KEY from .env)
# ---------------------------------------------------------------------------

import os
from groq import Groq
from dotenv import load_dotenv
from embeddings import load_index, search_index

load_dotenv()

# ---------------------------------------------------------------------------
# Groq client — reads GROQ_API_KEY from the environment
# ---------------------------------------------------------------------------
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Paths where the FAISS index and chunks are stored (must match app.py)
FAISS_INDEX_PATH = "vectorstore/faiss.index"
CHUNKS_PATH      = "vectorstore/chunks.json"

# Groq model — llama-3.1-8b-instant is free, fast, and actively supported
CHAT_MODEL = "llama-3.1-8b-instant"


def build_prompt(question: str, context_chunks: list[str]) -> str:
    """
    Combine retrieved context chunks and the user's question into a
    single grounded prompt string.

    Args:
        question:       The user's question.
        context_chunks: Relevant text passages retrieved from FAISS.

    Returns:
        A formatted prompt string ready to send to Groq.
    """
    context_block = "\n\n---\n\n".join(context_chunks)

    prompt = f"""You are a helpful knowledge assistant.
Answer the user's question using ONLY the context provided below.
If the answer is not found in the context, say:
"I could not find relevant information in the uploaded documents."

=== CONTEXT START ===
{context_block}
=== CONTEXT END ===

User Question: {question}

Answer:"""

    return prompt


def answer_question(question: str) -> dict:
    """
    Full RAG pipeline:
      1. Load the FAISS index and chunks from disk.
      2. Search for the most relevant chunks for the question.
      3. Build a grounded prompt from those chunks.
      4. Send to Groq Chat Completions (llama3-8b-8192).
      5. Return the answer and the source chunks used.

    Args:
        question: The user's question as a plain string.

    Returns:
        A dict with:
            "answer"  — the model's response string.
            "sources" — list of text chunks used as context.

    Raises:
        FileNotFoundError: If no document has been uploaded/indexed yet.
    """
    # ------------------------------------------------------------------ #
    # Step 1: Load the vector store from disk
    # ------------------------------------------------------------------ #
    index, chunks = load_index(FAISS_INDEX_PATH, CHUNKS_PATH)

    # ------------------------------------------------------------------ #
    # Step 2: Retrieve the top-5 most relevant chunks
    # ------------------------------------------------------------------ #
    relevant_chunks = search_index(
        query=question,
        index=index,
        chunks=chunks,
        top_k=5
    )

    if not relevant_chunks:
        return {
            "answer": "I could not find any relevant information in the "
                      "uploaded documents.",
            "sources": []
        }

    # ------------------------------------------------------------------ #
    # Step 3: Build the prompt with context
    # ------------------------------------------------------------------ #
    prompt = build_prompt(question, relevant_chunks)

    # ------------------------------------------------------------------ #
    # Step 4: Call Groq Chat API
    # ------------------------------------------------------------------ #
    response = groq_client.chat.completions.create(
        model=CHAT_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a precise and helpful knowledge assistant. "
                    "Only answer from the provided context. "
                    "Be concise and accurate."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2,
        max_tokens=1024
    )

    answer = response.choices[0].message.content.strip()
    print(f"[rag] Answer generated by Groq ({CHAT_MODEL}) successfully.")

    # ------------------------------------------------------------------ #
    # Step 5: Return the answer + source chunks for transparency
    # ------------------------------------------------------------------ #
    return {
        "answer": answer,
        "sources": relevant_chunks
    }